#!/usr/bin/env php
<?php

namespace Sanprojects\Interceptor;

use Sanprojects\Interceptor\Interceptor;

include $_composer_autoload_path ?? __DIR__ . '/../vendor/autoload.php';

Interceptor::interceptAll();
